"""Pydantic request/response schemas, grouped by domain.

Re-exported here so routers can import from one place, mirroring how
``app.models`` works.
"""

from app.schemas.auth import (
    AuthLoginRequest,
    AuthSignupRequest,
    AuthTriggerResponse,
    AuthVerifyRequest,
    AuthVerifyResponse,
)
from app.schemas.challenge import (
    ChallengeAssignmentOut,
    ChallengeBase,
    ChallengeCreate,
    ChallengeOut,
    ChallengeProgressOut,
    ChallengeUpdate,
    ProgressRequest,
    SegmentAssignRequest,
    SegmentAssignResult,
)
from app.schemas.email_verification import (
    DOITriggerRequest,
    DOITriggerResponse,
    DOIVerifyRequest,
    DOIVerifyResponse,
)
from app.schemas.event import (
    AddChallengeProgressEffect,
    AddPointsEffect,
    AddToSegmentEffect,
    AppliedEffectOut,
    AssignChallengeEffect,
    BurnPointsEffect,
    EventAttributeIn,
    EventAttributeOut,
    EventRuleCreate,
    EventRuleOut,
    EventRuleUpdate,
    EventTypeCreate,
    EventTypeOut,
    EventTypeUpdate,
    GrantRewardEffect,
    MemberEventOut,
    MemberFieldUpdate,
    RemoveFromSegmentEffect,
    RuleCondition,
    RuleEffect,
    TrackEventRequest,
    UpdateMemberEffect,
)
from app.schemas.member import (
    MemberCountOut,
    MemberCreate,
    MemberOut,
    MemberStatsOut,
    MemberUpdate,
)
from app.schemas.member_attribute import (
    MemberAttributeCreate,
    MemberAttributeOut,
    MemberAttributeUpdate,
)
from app.schemas.points import (
    AdjustPointsRequest,
    BalanceOut,
    EarnPointsRequest,
    PointsTransactionOut,
    SpendPointsRequest,
)
from app.schemas.product import ProductCreate, ProductOut, ProductUpdate
from app.schemas.program import (
    MemberProgramOut,
    ProgramCreate,
    ProgramOut,
    ProgramUpdate,
)
from app.schemas.purchase import PurchaseCreate, PurchaseOut, PurchaseStatsOut
from app.schemas.redemption import RedemptionOut
from app.schemas.reward import RewardCreate, RewardOut, RewardUpdate
from app.schemas.segment import (
    MemberAssignRequest,
    MemberAssignResult,
    SegmentBase,
    SegmentCreate,
    SegmentOut,
    SegmentSummary,
    SegmentUpdate,
)
from app.schemas.tier import TierBase, TierCreate, TierOut, TierUpdate

__all__ = [
    "AddChallengeProgressEffect",
    "AddPointsEffect",
    "AddToSegmentEffect",
    "AdjustPointsRequest",
    "AppliedEffectOut",
    "AssignChallengeEffect",
    "BurnPointsEffect",
    "AuthLoginRequest",
    "AuthSignupRequest",
    "AuthTriggerResponse",
    "AuthVerifyRequest",
    "AuthVerifyResponse",
    "BalanceOut",
    "ChallengeAssignmentOut",
    "ChallengeBase",
    "ChallengeCreate",
    "ChallengeOut",
    "ChallengeProgressOut",
    "ChallengeUpdate",
    "DOITriggerRequest",
    "DOITriggerResponse",
    "DOIVerifyRequest",
    "DOIVerifyResponse",
    "EarnPointsRequest",
    "EventAttributeIn",
    "EventAttributeOut",
    "EventRuleCreate",
    "EventRuleOut",
    "EventRuleUpdate",
    "EventTypeCreate",
    "EventTypeOut",
    "EventTypeUpdate",
    "GrantRewardEffect",
    "MemberAssignRequest",
    "MemberAssignResult",
    "MemberAttributeCreate",
    "MemberAttributeOut",
    "MemberAttributeUpdate",
    "MemberCountOut",
    "MemberCreate",
    "MemberEventOut",
    "MemberFieldUpdate",
    "MemberProgramOut",
    "MemberOut",
    "MemberStatsOut",
    "MemberUpdate",
    "PointsTransactionOut",
    "ProductCreate",
    "ProductOut",
    "ProductUpdate",
    "ProgramCreate",
    "ProgramOut",
    "ProgramUpdate",
    "ProgressRequest",
    "PurchaseCreate",
    "PurchaseOut",
    "PurchaseStatsOut",
    "RedemptionOut",
    "RemoveFromSegmentEffect",
    "RewardCreate",
    "RewardOut",
    "RewardUpdate",
    "RuleCondition",
    "RuleEffect",
    "SegmentAssignRequest",
    "SegmentAssignResult",
    "SegmentBase",
    "SegmentCreate",
    "SegmentOut",
    "SegmentSummary",
    "SegmentUpdate",
    "SpendPointsRequest",
    "TierBase",
    "TierCreate",
    "TierOut",
    "TierUpdate",
    "TrackEventRequest",
    "UpdateMemberEffect",
]
